name: build-and-test
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        mode: [release, address, thread]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Configure
        run: |
          extra=""
          [ '${{ matrix.mode }}' != address ] || extra=-DXA_SANITIZE_ADDRESS=ON
          [ '${{ matrix.mode }}' != thread ] || extra=-DXA_SANITIZE_THREAD=ON
          cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo $extra
      - run: cmake --build build --parallel 2
      - run: ctest --test-dir build --output-on-failure
